# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regipn: [ ap-southeast-1, ap-southeast-2, ap-northeast-1, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1,  eu-west-1,  eu-west-2,  eu-west-3, eu-north-1, eu-south-1,  me-south-1 ,sa-east-1, us-gov-east-1, us-gov-west-1 ]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: terraform validate -var region=${{ matrix.version }}
