# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fixtures:
          [
            "services/default",
            "services/1-item",
            "region/ap-southeast-1",
            "region/ap-southeast-2",
            "region/ap-northeast-1",
            "region/ca-central-1",
            "region/cn-north-1",
            "region/cn-northwest-1",
            "region/eu-central-1",
            "region/eu-west-1",
            "region/eu-west-2",
            "region/eu-west-3",
            "region/eu-north-1",
            "region/eu-south-1",
            "region/me-south-1",
            "region/sa-east-1",
            "region/us-east-1",
            "region/us-east-2",
            "region/us-west-1",
            "region/us-west-2",
            "region/us-gov-east-1",
            "region/us-gov-west-1",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Run a Terraform Plan for all regions
        run: |
          terraform init
          terraform plan -var-file ./fixtures/${{ matrix.fixtures }}.tfvars
